export const CANONICAL_KEYS = {
  NEXT_PUBLIC_SUPABASE_URL: 'NEXT_PUBLIC_SUPABASE_URL',
  NEXT_PUBLIC_SUPABASE_ANON_KEY: 'NEXT_PUBLIC_SUPABASE_ANON_KEY',
  PUBLIC_APP_NAME: 'PUBLIC_APP_NAME',
  SUPABASE_SERVICE_ROLE_KEY: 'SUPABASE_SERVICE_ROLE_KEY',
  ODDS_API_KEY: 'ODDS_API_KEY',
  ODDS_API_BASE_URL: 'ODDS_API_BASE_URL',
  SPORTSDATA_API_KEY: 'SPORTSDATA_API_KEY',
  LIVE_MODE: 'LIVE_MODE',
  CRON_SECRET: 'CRON_SECRET',
} as const;

export const ALIAS_KEYS = {
  [CANONICAL_KEYS.ODDS_API_KEY]: ['THEODDSAPI_KEY'],
  [CANONICAL_KEYS.SPORTSDATA_API_KEY]: ['SPORTSDATAIO_API_KEY'],
} as const;

export type CanonicalEnvKey = (typeof CANONICAL_KEYS)[keyof typeof CANONICAL_KEYS];
